# Configuration file for the autocommissioner program - PAE - Jaume Colom

# Device related configs
device: 
  device_type: 'Mock'         # Options are: 'USB', 'Mock' and 'HTTP' (although not implemented)
  mock_config:  
    number: 20                # Number of devices to create
  tty_config:
  http_config:
  commissioner_device_id: 1   # Id of the device to be the commissioner and to receive the udp messages
  udp_receiver_id: 1
# Topology related configs
topology:
  topology_type: 'all_to_one' # Currently only implemented 'all_to_one'
  plot: True                 # Requires the networkX package
# Terminal flag
open_terms: True
threading: True
logger:
  format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  level: 'DEBUG'
